CREATE DATABASE `db_zarplata_event`

CREATE TABLE `events` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`description` VARCHAR(400) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`content` VARCHAR(400) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`is_current` TINYINT(1) UNSIGNED NULL DEFAULT '0',
	`date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;

CREATE TABLE `users` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`tg_id` BIGINT UNSIGNED NOT NULL,
	`event_id` INT(10) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `event_id` (`event_id`) USING BTREE,
	UNIQUE INDEX `tg_id` (`tg_id`),
	CONSTRAINT `FK__users_events` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;

CREATE TABLE `moderators` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`tg_id` BIGINT UNSIGNED NOT NULL,
	`event_id` INT(10) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `event_id` (`event_id`) USING BTREE,
	UNIQUE INDEX `tg_id` (`tg_id`),
	CONSTRAINT `FK__moderators_events` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;

CREATE TABLE `speakers` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`tg_id` BIGINT UNSIGNED NOT NULL,
	`name` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`event_id` INT(10) UNSIGNED NULL DEFAULT NULL,
	`is_current` TINYINT(1) UNSIGNED NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `event_id` (`event_id`) USING BTREE,
	UNIQUE INDEX `tg_id` (`tg_id`),
	CONSTRAINT `FK__speakers_events` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;